### ISSUE TITLE
Verifications

### ISSUE THREAD

**Issue by ferbsx** [rubymonsters/new_monsters#4]
- ignore spaces on location verifications
- fix presence verification for female field
- add error message for female field presence
- fix presence verification for beginner field
- add error message for beginner field presence

![screen shot 2015-08-09 at 11 51 05 pm](https://cloud.githubusercontent.com/assets/11502220/9157126/29eac6e4-3ef2-11e5-90b9-595d5a3fc91d.png)

**Comment by ferbsx** [comment]
- ignore spaces on location verifications
- :new: fix twitter handle verifications, it needs to accept numbers and -
- :heavy_check_mark: fix presence verification for female field
- :heavy_check_mark: add error message for female field presence
- :heavy_check_mark: fix presence verification for beginner field
- :heavy_check_mark: add error message for beginner field presence
  ![screen shot 2015-08-10 at 8 32 32 pm](https://cloud.githubusercontent.com/assets/11502220/9179853/6d764d90-3f9f-11e5-958c-260bebda15cc.png)

**Comment by ferbsx** [comment]
ALL DONE! :smiley:

**Comment by ariaru** [comment]
Cool! :)

Date: Mon, 10 Aug 2015 16:17:20 -0700
